runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /pixi
  static_dir: pixi
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
